### ISSUE TITLE
ArrayOfLineItem.setLineItemList missing in release 0.11

### ISSUE THREAD

**Issue by jbroberg** [connectifier/xero-java-client#3]
ArrayOfLineItem.setLineItemList seems to be missing in most recent release (0.11), which makes creating an invoice a bit challenging.

Rolling back to maven release 0.10 fixes the issue for me.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project admin: Compilation failure
[ERROR] /Users/brobergj/workspace/admin/src/test/java/org/unimelb/metacdn/admin/reporting/XeroTest.java:[54,21] cannot find symbol
[ERROR] symbol:   method setLineItemList(java.util.List<com.connectifier.xeroclient.models.LineItem>)
[ERROR] location: variable aoli of type com.connectifier.xeroclient.models.ArrayOfLineItem
[ERROR] -> [Help 1]

Many thanks for the Java API btw.

**Comment by benmccann** [comment]
You can call `ArrayOfLineItem.getLineItemList().addAll()`. It does seem there's still another problem with creating invoices in 0.11 though

**Comment by benmccann** [comment]
Creating invoices should be fixed again with the 0.12 release

**Comment by benmccann** [comment]
Turns out this was broken in 0.12 still. Release 0.13 to fix it and add `setLineItems()` method
